Старт


In [ ]:
print("hello, Darya!")

hello, Darya!


1.1. Реализовать функцию REF(), приводящую матрицу к ступенчатому виду.

In [ ]:
import numpy as np
import itertools as iter

In [ ]:
def matrixRowXor(row1, row2, k):
    for i in range(k, len(row1)):
        row2[i] ^= row1[i]

In [ ]:
def ref(matrix):
    k = -1
    for j in range(len(matrix[0])):
        b = True
        for i in range(k+1, len(matrix)):
            if matrix[i][j] == 1:
                if b:
                    k += 1
                    c = matrix[k]
                    matrix[k] = matrix[i]
                    matrix[i] = c
                    b = False
                else:
                    matrixRowXor(matrix[k], matrix[i], j)
    return k + 1

1.2. Реализовать функцию RREF(), приводящую матрицу к
приведённому ступенчатому виду.

In [ ]:
def rref(matrix):
    k = 0
    lead = []
    i = 0
    while k < len(matrix):
        if matrix[k][i] == 1:
            for j in range(0, k):
                if matrix[j][i] == 1:
                    matrixRowXor(matrix[k], matrix[j], i)
            lead.append(i)
            k += 1
        i += 1
    return lead

In [ ]:
def createX(matrix, lead):
    X = []
    k = 0
    for i in range(len(matrix[0])):
        if k == -1 or i < lead[k]:
            X.append(matrix[:,i])
        else:
            k += 1
            if k == len(lead):
                k = -1
    return np.array(X).T

In [ ]:
def createH(X, I, n, lead):
    H = []
    k_x = k_lead = 0
    for i in range(n):
        if k_x == -1 or i < lead[k_x]:
            H.append(I[k_lead])
            k_lead += 1
        else:
            H.append(X[k_x])
            k_x += 1
            if k_x == len(lead):
                k_x = -1
    return np.array(H)

In [ ]:
def createAllWordsLengthK(k):
    all_words_k = np.array(list(iter.product((0, 1), repeat=5)))
    return all_words_k

In [ ]:
def createCodeWordsLengthN(G, k):
    code_words_n_length = [[0] * len(G[0])]
    for i in range(1, k + 1):
        for arr in np.array(list(iter.combinations(G, i))):
            code_words_n_length.append(sum(arr) % 2)
    return np.array(code_words_n_length)

In [ ]:
def comparison(array1, array2):
    # так как это бинарные массивы, то каждую строчку можно представить в виде десятичного числа
    # представим оба массива бинарных строк в виде массивов с числами, отсортируем их и сравним
    arr1 = []
    arr2 = []
    n = len(array1[0]) - 1
    for row in array1:
        arr1.append(sum([row[i] * 2**i for i in range(n)]))
    arr1.sort()
    for row in array2:
        arr2.append(sum([row[i] * 2**i for i in range(n)]))
    arr2.sort()
    for i in range(n):
        if arr1[i] != arr2[i]:
            return False
    return True

In [ ]:
def findCodeDistance(C):
    d = min([sum(i) for i in C[1:]])
    t = d // 2
    return d, t

In [ ]:
# начальная матрица
S = [[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
    [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]]
S = np.array(S)
S

array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]])

1.3.1 На основе входной матрицы сформировать порождающую матрицу в ступенчатом виде.


In [ ]:
# ранг матрицы
k = ref(S)

# порождающая матрица
G = S[:k]
G

array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

1.3.3 Сформировать проверочную матрицу на основе порождающей.

Шаг 1. Сформировать матрицу 𝐆∗ в приведённом ступенчатом виде на основе порождающей.

In [ ]:
# приведённая матрица в ступенчатом виде
G_ = G.copy()
n = len(G_[0])

# ведущие столбцы
lead = rref(G_)
G_

array([[1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

1.3.2 Задать n равное числу столбцов и k равное числу строк полученной матрицы

In [ ]:
n, k

(11, 5)

Шаг 2. Зафиксировать ведущие столбцы lead матрицы 𝐆∗


In [ ]:
lead

[0, 3, 4, 6, 8]

Шаг 3. Сформировать сокращённую матрицу 𝐗, удалив ведущие столбцы матрицы 𝐆∗


In [ ]:
X = createX(G_.copy(), lead)
X

array([[0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1]])

Шаг 4. Сформировать матрицу 𝐇, поместив в строки, соответствующие позициям ведущих столбцов строки из 𝐗, а в остальные – строки единичной матрицы.

In [ ]:
I = np.eye(n-k, dtype=int)
I

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [ ]:
H = createH(X.copy(), I.copy(), n, lead)
H

array([[0, 1, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

1.4.2 Взять все двоичные слова длины k, умножить каждое на G.

In [ ]:
# создаём все возможные слова длинной k
all_words_k = createAllWordsLengthK(k)
all_words_k

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [ ]:
# создадим все кодовые слова вторым способом
C = np.dot(all_words_k, G) % 2
C

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
       [1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 1, 0, 1,

1.4.1 Сложить все слова из порождающего множества, оставить
неповторяющиеся.

In [ ]:
# создадим все кодовые слова первым способом
C2 = createCodeWordsLengthN(G, k)
C2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 1,

In [ ]:
 # проверим равенство
comparison(C, C2)

True

In [ ]:
# проверим все кодовые слова, умножив их на проверочную матрицу (должна получиться матрица из нулей)
np.dot(C, H) % 2

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

1.4 Вычислить кодовое расстояние получившегося кода.

In [ ]:
# найдём кодовое расстояние и максимальную кратность обнаруживаемой ошибки
d, t = findCodeDistance(C)
d, t

(2, 1)

1.4.1 Внести в кодовое слово ошибку кратности не более t, умножить
полученное слово на H, убедиться в обнаружении ошибки.

In [ ]:
e1 = np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])
C_ =  np.dot(C.copy() + e1, H) % 2  # тут вносим ошибку кратности t во все кодовые слова для проверки
C_  # должен получиться массив, каждая из строчек которого содержит хотя бы одну единицу

array([[0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0]])

1.4.2 Найти для некоторого кодового слова ошибку кратности t+1 такую, что при умножении на H ошибка не может быть обнаружена.

In [ ]:
e2 = np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0])
v = S[1].copy()
v += e2
np.dot(v, H) % 2

array([0, 0, 0, 0, 0, 0])