In [120]:
import numpy as np
import math
import itertools as iter

In [121]:
# функция вычисления n и k на основе r
def calculate_n_k(r):
    n = int(math.pow(2, r) - 1)
    k = n - r
    return n, k

In [122]:
# функция создания таблицы синдромов
def create_syndrome_table(H, err_count):
    n = len(H)
    one_err = np.eye(n, dtype=int)
    syndrome_table = {H[i].__str__(): one_err[i] for i in range(n)}

    for num in range(2, err_count + 1):
        syndrome_arr = [sum(arr) % 2 for arr in np.array(list(iter.combinations(H, num)))]
        err_arr = [sum(arr) for arr in np.array(list(iter.combinations(one_err, num)))]
        for i in range(len(syndrome_arr)):
            syndrome_table[syndrome_arr[i].__str__()] = err_arr[i]

    return syndrome_table

**3.1 Написать функцию формирования порождающей и проверочной
матриц кода Хэмминга (𝟐
𝒓 − 𝟏, 𝟐
𝒓 − 𝒓 − 𝟏, 𝟑) на основе параметра 𝒓,
а также таблицы синдромов для всех однократных ошибок.**

In [123]:
# функция создания проверочной матрицы Хемминга
def create_hamming(n, r):
    E = np.eye(r,dtype=int)
    H = []
    for i in range(r, 0, -1):
        for synd in [sum(arr) for arr in np.array(list(iter.combinations(E, i)))]:
            H.append(synd)
    return np.array(H)

In [124]:
# функция создания порождающей матрицы
def create_G(H, n, k):
    G = np.zeros((k, n), dtype=int)
    for i in range(k):
        G[i][i] = 1
    G[:, k:] = H[:k, :]
    return G

**3.2. Провести исследование кода Хэмминга для одно-, двух- и
трёхкратных ошибок для 𝒓 = 𝟐, 𝟑, 𝟒.**

для r = 2

In [125]:
r = 2
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H = create_hamming(n, r)
print('H =', H, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G = create_G(H, n, k)
print('G =', G, sep='\n', end='\n\n')
syndrome_table = create_syndrome_table(H, 1)

n = 3, k = 1, d = 3

H =
[[1 1]
 [1 0]
 [0 1]]

G =
[[1 1 1]]



In [126]:
word = np.array([1])
code = np.dot(word, G)
print(f'кодовое слово = {code}', end='\n\n')

error1 = np.array([1, 0, 0])
error2 = np.array([1, 0, 1])
error3 = np.array([1, 1, 1])

err_code1 = code ^ error1
err_code2 = code ^ error2
err_code3 = code ^ error3

syndrome1 = np.dot(err_code1, H) % 2
syndrome2 = np.dot(err_code2, H) % 2
syndrome3 = np.dot(err_code3, H) % 2
print(f'синдром 1 = {syndrome1}, синдром 2 = {syndrome2}, синдром 3 = {syndrome3}', end='\n\n')

кодовое слово = [1 1 1]

синдром 1 = [1 1], синдром 2 = [1 0], синдром 3 = [0 0]



In [127]:
print('для однократной ошибки можем обнаружить, но не исправить:')
if not np.array_equal(syndrome1, np.zeros(r, dtype=int)):
    print(f'ошибка в разряде: {syndrome_table[syndrome1.__str__()]}', end='\n\n')
else:
  print('ошибки нет', end='\n\n')

print('для двукратной ошибки можем только обнаружить:')
if not np.array_equal(syndrome2, np.zeros(r, dtype=int)):
    print(f'ошибка в разряде: {syndrome_table[syndrome2.__str__()]}', end='\n\n')
else:
  print('ошибки нет', end='\n\n')

print('с трёхкратной ошибкой ничего сделать нельзя:')
if not np.array_equal(syndrome3, np.zeros(r, dtype=int)):
    print(f'ошибка в разряде: {syndrome_table[syndrome3.__str__()]}', end='\n\n')
else:
  print('ошибки нет', end='\n\n')

для однократной ошибки можем обнаружить, но не исправить:
ошибка в разряде: [1 0 0]

для двукратной ошибки можем только обнаружить:
ошибка в разряде: [0 1 0]

с трёхкратной ошибкой ничего сделать нельзя:
ошибки нет



для r = 3

In [128]:
r = 3
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H = create_hamming(n, r)
print('H =', H, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G = create_G(H, n, k)
print('G =', G, sep='\n', end='\n\n')
syndrome_table = create_syndrome_table(H, 1)

n = 7, k = 4, d = 3

H =
[[1 1 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]

G =
[[1 0 0 0 1 1 1]
 [0 1 0 0 1 1 0]
 [0 0 1 0 1 0 1]
 [0 0 0 1 0 1 1]]



In [129]:
word = np.array([1, 0, 0, 0])
code = np.dot(word, G)
print(f'кодовое слово = {code}', end='\n\n')

error1 = np.array([1, 0, 0, 0, 0, 0, 0])
error2 = np.array([1, 1, 0, 0, 0, 0, 0])
error3 = np.array([1, 1, 0, 0, 0, 0, 1])

err_code1 = code ^ error1
err_code2 = code ^ error2
err_code3 = code ^ error3

syndrome1 = np.dot(err_code1, H) % 2
syndrome2 = np.dot(err_code2, H) % 2
syndrome3 = np.dot(err_code3, H) % 2
print(f'синдром 1 = {syndrome1}, синдром 2 = {syndrome2}, синдром 3 = {syndrome3}', end='\n\n')

кодовое слово = [1 0 0 0 1 1 1]

синдром 1 = [1 1 1], синдром 2 = [0 0 1], синдром 3 = [0 0 0]



In [130]:
print('для однократной ошибки можем обнаружить, но не исправить:')
if not np.array_equal(syndrome1, np.zeros(r, dtype=int)):
    print(f'ошибка в разряде: {syndrome_table[syndrome1.__str__()]}', end='\n\n')
else:
  print('ошибки нет', end='\n\n')

print('для двукратной ошибки можем только обнаружить:')
if not np.array_equal(syndrome2, np.zeros(r, dtype=int)):
    print(f'ошибка в разряде: {syndrome_table[syndrome2.__str__()]}', end='\n\n')
else:
  print('ошибки нет', end='\n\n')

print('с трёхкратной ошибкой ничего сделать нельзя:')
if not np.array_equal(syndrome3, np.zeros(r, dtype=int)):
    print(f'ошибка в разряде: {syndrome_table[syndrome3.__str__()]}', end='\n\n')
else:
  print('ошибки нет', end='\n\n')

для однократной ошибки можем обнаружить, но не исправить:
ошибка в разряде: [1 0 0 0 0 0 0]

для двукратной ошибки можем только обнаружить:
ошибка в разряде: [0 0 0 0 0 0 1]

с трёхкратной ошибкой ничего сделать нельзя:
ошибки нет



для r = 4

In [131]:
r = 4
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H = create_hamming(n, r)
print('H =', H, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G = create_G(H, n, k)
print('G =', G, sep='\n', end='\n\n')
syndrome_table = create_syndrome_table(H, 1)

n = 15, k = 11, d = 3

H =
[[1 1 1 1]
 [1 1 1 0]
 [1 1 0 1]
 [1 0 1 1]
 [0 1 1 1]
 [1 1 0 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 1 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

G =
[[1 0 0 0 0 0 0 0 0 0 0 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 1 1 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1]]



In [132]:
word = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
code = np.dot(word, G)
print(f'кодовое слово = {code}', end='\n\n')

error1 = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
error2 = np.array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
error3 = np.array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

err_code1 = code ^ error1
err_code2 = code ^ error2
err_code3 = code ^ error3

syndrome1 = np.dot(err_code1, H) % 2
syndrome2 = np.dot(err_code2, H) % 2
syndrome3 = np.dot(err_code3, H) % 2
print(f'синдром 1 = {syndrome1}, синдром 2 = {syndrome2}, синдром 3 = {syndrome3}', end='\n\n')

кодовое слово = [1 0 0 0 0 0 0 0 0 0 0 1 1 1 1]

синдром 1 = [1 1 1 1], синдром 2 = [0 0 0 1], синдром 3 = [0 0 0 0]



In [133]:
print('для однократной ошибки можем обнаружить, но не исправить:')
if not np.array_equal(syndrome1, np.zeros(r, dtype=int)):
    print(f'ошибка в разряде: {syndrome_table[syndrome1.__str__()]}', end='\n\n')
else:
  print('ошибки нет', end='\n\n')

print('для двукратной ошибки можем только обнаружить:')
if not np.array_equal(syndrome2, np.zeros(r, dtype=int)):
    print(f'ошибка в разряде: {syndrome_table[syndrome2.__str__()]}', end='\n\n')
else:
  print('ошибки нет', end='\n\n')

print('с трёхкратной ошибкой ничего сделать нельзя:')
if not np.array_equal(syndrome3, np.zeros(r, dtype=int)):
    print(f'ошибка в разряде: {syndrome_table[syndrome3.__str__()]}', end='\n\n')
else:
  print('ошибки нет', end='\n\n')

для однократной ошибки можем обнаружить, но не исправить:
ошибка в разряде: [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

для двукратной ошибки можем только обнаружить:
ошибка в разряде: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]

с трёхкратной ошибкой ничего сделать нельзя:
ошибки нет



**3.3 Написать функцию формирования порождающей и проверочной
матриц расширенного кода Хэмминга (𝟐
𝒓
, 𝟐
𝒓 − 𝒓 − 𝟏, 𝟑) на основе
параметра 𝒓, а также таблицы синдромов для всех однократных
ошибок.**

In [134]:
# функция создания проверочной расширенной матрицы Хемминга
def create_advanced_hamming(n, r):
    H_ = np.zeros((n+1, r+1), dtype=int)
    H_[:n,:r] = create_hamming(n, r)
    H_[:,r] += 1
    return H_

In [135]:
# функция создания расширенной порождающей матрицы
def create_advanced_G(H_, n, k):
    G_ = np.zeros((k, n+1), dtype=int)
    G_[:, :n] = create_G(H_[:n, :n-k], n, k)
    for i in range(k):
        G_[i][n] = sum(G_[i]) % 2
    return G_

**3.4. Провести исследование расширенного кода Хэмминга для одно-,
двух-, трёх- и четырёхкратных ошибок для 𝒓 = 𝟐, 𝟑, 𝟒.**

для r = 2

In [136]:
r = 2
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H_ = create_advanced_hamming(n, r)
print('H_ =', H_, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G_ = create_advanced_G(H_, n, k)
print('G_ =', G_, sep='\n', end='\n\n')
syndrome_table = create_syndrome_table(H_, 1)

n = 3, k = 1, d = 3

H_ =
[[1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 1]]

G_ =
[[1 1 1 1]]



In [137]:
word = np.array([1])
code = np.dot(word, G_)
print(f'кодовое слово = {code}', end='\n\n')

error1 = np.array([1, 0, 0, 0])
error2 = np.array([1, 0, 1, 0])
error3 = np.array([1, 1, 0, 1])
error4 = np.array([1, 1, 1, 1])

err_code1 = code ^ error1
err_code2 = code ^ error2
err_code3 = code ^ error3
err_code4 = code ^ error4

syndrome1 = np.dot(err_code1, H_) % 2
syndrome2 = np.dot(err_code2, H_) % 2
syndrome3 = np.dot(err_code3, H_) % 2
syndrome4 = np.dot(err_code4, H_) % 2
print(f'синдром 1 = {syndrome1}, синдром 2 = {syndrome2}, синдром 3 = {syndrome3}, синдром 4 = {syndrome4}')

кодовое слово = [1 1 1 1]

синдром 1 = [1 1 1], синдром 2 = [1 0 0], синдром 3 = [0 1 1], синдром 4 = [0 0 0]


In [138]:
def find_error(syndrome, r):
    if not np.array_equal(syndrome, np.zeros(r+1, dtype=int)):
        if syndrome[r] == 0:
            print('двукратная ошибка', end='\n\n')
        else:
          print(f'ошибка в разряде: {syndrome_table[syndrome.__str__()]}', end='\n\n')
    else:
        print('ошибок нет', end='\n\n')

In [139]:
print('для однократной ошибки можем обнаружить, но не исправить:')
find_error(syndrome1, r)
print('для двукратной ошибки можем обнаружить и распознать:')
find_error(syndrome2, r)
print('трёхкратную ошибку можем только обнаружить:')
find_error(syndrome3, r)
print('с четырёхкратной ошибкой ничего сделать нельзя:')
find_error(syndrome4, r)

для однократной ошибки можем обнаружить, но не исправить:
ошибка в разряде: [1 0 0 0]

для двукратной ошибки можем обнаружить и распознать:
двукратная ошибка

трёхкратную ошибку можем только обнаружить:
ошибка в разряде: [0 0 1 0]

с четырёхкратной ошибкой ничего сделать нельзя:
ошибок нет



для r = 3

In [140]:
r = 3
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H_ = create_advanced_hamming(n, r)
print('H_ =', H_, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G_ = create_advanced_G(H_, n, k)
print('G_ =', G_, sep='\n', end='\n\n')
syndrome_table = create_syndrome_table(H_, 1)

n = 7, k = 4, d = 3

H_ =
[[1 1 1 1]
 [1 1 0 1]
 [1 0 1 1]
 [0 1 1 1]
 [1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 1]]

G_ =
[[1 0 0 0 1 1 1 0]
 [0 1 0 0 1 1 0 1]
 [0 0 1 0 1 0 1 1]
 [0 0 0 1 0 1 1 1]]



In [141]:
word = np.array([1, 0, 0, 1])
code = np.dot(word, G_)
print(f'кодовое слово = {code}', end='\n\n')

error1 = np.array([1, 0, 0, 0, 0, 0, 0, 0])
error2 = np.array([1, 1, 0, 0, 0, 0, 0, 0])
error3 = np.array([1, 1, 0, 0, 0, 0, 1, 0])
error4 = np.array([1, 1, 0, 0, 0, 0, 1, 1])

err_code1 = code ^ error1
err_code2 = code ^ error2
err_code3 = code ^ error3
err_code4 = code ^ error4

syndrome1 = np.dot(err_code1, H_) % 2
syndrome2 = np.dot(err_code2, H_) % 2
syndrome3 = np.dot(err_code3, H_) % 2
syndrome4 = np.dot(err_code4, H_) % 2
print(f'синдром 1 = {syndrome1}, синдром 2 = {syndrome2}, синдром 3 = {syndrome3}, синдром 4 = {syndrome4}')

кодовое слово = [1 0 0 1 1 2 2 1]

синдром 1 = [1 1 1 1], синдром 2 = [0 0 1 0], синдром 3 = [0 0 0 1], синдром 4 = [0 0 0 0]


In [142]:
print('для однократной ошибки можем обнаружить, но не исправить:')
find_error(syndrome1, r)
print('для двукратной ошибки можем обнаружить и распознать:')
find_error(syndrome2, r)
print('трёхкратную ошибку можем только обнаружить:')
find_error(syndrome3, r)
print('с четырёхкратной ошибкой ничего сделать нельзя:')
find_error(syndrome4, r)

для однократной ошибки можем обнаружить, но не исправить:
ошибка в разряде: [1 0 0 0 0 0 0 0]

для двукратной ошибки можем обнаружить и распознать:
двукратная ошибка

трёхкратную ошибку можем только обнаружить:
ошибка в разряде: [0 0 0 0 0 0 0 1]

с четырёхкратной ошибкой ничего сделать нельзя:
ошибок нет



для r = 4

In [143]:
r = 4
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H_ = create_advanced_hamming(n, r)
print('H_ =', H_, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G_ = create_advanced_G(H_, n, k)
print('G_ =', G_, sep='\n', end='\n\n')
syndrome_table = create_syndrome_table(H_, 1)

n = 15, k = 11, d = 3

H_ =
[[1 1 1 1 1]
 [1 1 1 0 1]
 [1 1 0 1 1]
 [1 0 1 1 1]
 [0 1 1 1 1]
 [1 1 0 0 1]
 [1 0 1 0 1]
 [1 0 0 1 1]
 [0 1 1 0 1]
 [0 1 0 1 1]
 [0 0 1 1 1]
 [1 0 0 0 1]
 [0 1 0 0 1]
 [0 0 1 0 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]

G_ =
[[1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1]]



In [144]:
word = np.array([1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0])
code = np.dot(word, G_)
print(f'кодовое слово = {code}', end='\n\n')

error1 = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
error2 = np.array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
error3 = np.array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0])
error4 = np.array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0])

err_code1 = code ^ error1
err_code2 = code ^ error2
err_code3 = code ^ error3
err_code4 = code ^ error4

syndrome1 = np.dot(err_code1, H_) % 2
syndrome2 = np.dot(err_code2, H_) % 2
syndrome3 = np.dot(err_code3, H_) % 2
syndrome4 = np.dot(err_code4, H_) % 2
print(f'синдром 1 = {syndrome1}, синдром 2 = {syndrome2}, синдром 3 = {syndrome3}, синдром 4 = {syndrome4}')

кодовое слово = [1 0 0 1 0 1 0 0 1 0 0 3 3 3 2 3]

синдром 1 = [1 1 1 1 1], синдром 2 = [1 0 0 0 0], синдром 3 = [0 0 1 0 1], синдром 4 = [0 0 0 0 0]


In [145]:
print('для однократной ошибки можем обнаружить, но не исправить:')
find_error(syndrome1, r)
print('для двукратной ошибки можем обнаружить и распознать:')
find_error(syndrome2, r)
print('трёхкратную ошибку можем только обнаружить:')
find_error(syndrome3, r)
print('с четырёхкратной ошибкой ничего сделать нельзя:')
find_error(syndrome4, r)

для однократной ошибки можем обнаружить, но не исправить:
ошибка в разряде: [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

для двукратной ошибки можем обнаружить и распознать:
двукратная ошибка

трёхкратную ошибку можем только обнаружить:
ошибка в разряде: [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]

с четырёхкратной ошибкой ничего сделать нельзя:
ошибок нет

