**Часть 1**

In [2]:
import numpy as np
n, k, d = 24, 12, 8

**4.1 Написать функцию формирования порождающей и проверочной матриц расширенного кода Голея (24,12,8).**

In [3]:
#необходимые для работы функции
def create_H(b_matr):
    H = np.zeros((n, k), dtype=int)
    for i in range(k):
        H[i][i] = 1
    H[k:, :] = b_matr
    return H


def create_G(H):
    G = np.zeros((k, n), dtype=int)
    for i in range(k):
        G[i][i] = 1
    G[:, k:] = H[k:, :]
    return G


def create_B() -> np.ndarray:
    rolled_mas = np.array([1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0])
    result = np.zeros((11, 11), dtype=int)
    result[0] = rolled_mas
    for i in range(1, k-1):
        rolled_mas = np.roll(rolled_mas, -1)
        result[i] = rolled_mas

    last_row_col = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

    result = np.r_[result, [last_row_col]]
    last_row_col = np.append(last_row_col, 0)
    result = np.column_stack((result, last_row_col))
    return result

In [4]:
def hemming_weight(word):
  return np.sum(word)
    # return np.count_nonzero(word == 1)


def golay_approach(H, B, err_code):
    syndrome = np.dot(err_code, H) % 2
    print(f'Синдром ошибки: {syndrome}')
    if hemming_weight(syndrome) <= 3:
        print("Вес Хэмминга синдрома меньше или равен 3")
        caught_error = np.zeros(24, dtype=int)
        caught_error[:12] = syndrome
        print(f'Ошибка: {caught_error}')
        correct_word = caught_error ^ err_code
        return correct_word[:12]
    else:
        print("Вес Хэмминга синдрома больше 3")
        for i in range(12):
            if hemming_weight(syndrome ^ B[i][:]) <= 2:
                print(f'Существует строка {i} матрицы B, такая, что wt(s+b[i]) <=2')
                caught_error = np.zeros(24, dtype=int)
                caught_error[12+i] = 1
                caught_error[:12] = syndrome ^ B[i][:]
                print(f'Ошибка: {caught_error}')
                correct_word = caught_error ^ err_code
                return correct_word[:12]

        print('Не существует строк матрицы B, таких, что wt(s+b[i]) <=2')
        second_syndrome = np.dot(syndrome, B) % 2
        if hemming_weight(second_syndrome) <= 3:
            print("Вес Хэмминга второго синдрома(s*B) меньше или равен 3")
            caught_error = np.zeros(24, dtype=int)
            caught_error[12:] = second_syndrome
            print(f'Ошибка: {caught_error}')
            correct_word = caught_error ^ err_code
            return correct_word[:12]
        else:
            print("Вес Хэмминга второго синдрома(s*B) больше 3")
            for i in range(12):
                if hemming_weight(second_syndrome ^ B[i][:]) <= 2:
                    print(f'Существует строка {i} матрицы B, такая, что wt(s*B+b[i]) <=2')
                    caught_error = np.zeros(24, dtype=int)
                    caught_error[i] = 1
                    caught_error[12:] = second_syndrome ^ B[i][:]
                    print(f'Ошибка: {caught_error}')
                    correct_word = caught_error ^ err_code
                    return correct_word[:12]
            print('Не существует строк матрицы B, таких, что wt(s*B+b[i]) <=2')
    print("В коде от 4 до 7 ошибок.")
    return None


**4.2. Провести исследование расширенного кода Голея для одно-, двух-, трёх- и четырёхкратных ошибок.**

In [5]:
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')
B = create_B()
H = create_H(B)
print(f' H = \n{H}')
G = create_G(H)
print(f' G = \n{G}\n')

n = 24, k = 12, d = 8

 H = 
[[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 0 0 0 1 0 1]
 [1 0 1 1 1 0 0 0 1 0 1 1]
 [0 1 1 1 0 0 0 1 0 1 1 1]
 [1 1 1 0 0 0 1 0 1 1 0 1]
 [1 1 0 0 0 1 0 1 1 0 1 1]
 [1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 1 0 1 1 0 1 1 1 0 1]
 [0 1 0 1 1 0 1 1 1 0 0 1]
 [1 0 1 1 0 1 1 1 0 0 0 1]
 [0 1 1 0 1 1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0]]
 G = 
[[1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 0 

In [6]:
message = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
code_word = np.dot(message, G) % 2
print(f'кодовое слово: {code_word}')

кодовое слово: [1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]


Однократная ошибка

In [7]:
error_one = np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
err_code = code_word ^ error_one

decoded_word = golay_approach(H, B, err_code)
if decoded_word is None:
    print("Отправьте сообщение повторно")
else:
    print(f'Исправленное сообщение: {decoded_word}')

Синдром ошибки: [0 1 0 0 0 0 0 0 0 0 0 0]
Вес Хэмминга синдрома меньше или равен 3
Ошибка: [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Исправленное сообщение: [1 0 0 0 0 0 0 0 0 0 0 0]


Двукратная ошибка

In [8]:
error_two = np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
err_code = code_word ^ error_two

decoded_word = golay_approach(H, B, err_code)
if decoded_word is None:
    print("Отправьте сообщение повторно")
else:
    print(f'Исправленное сообщение: {decoded_word}')

Синдром ошибки: [0 1 0 1 0 1 1 0 1 1 1 1]
Вес Хэмминга синдрома больше 3
Существует строка 6 матрицы B, такая, что wt(s+b[i]) <=2
Ошибка: [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
Исправленное сообщение: [1 0 0 0 0 0 0 0 0 0 0 0]


Трёхкратная ошибка

In [9]:
error_three = np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])
err_code = code_word ^ error_three

decoded_word = golay_approach(H, B, err_code)
if decoded_word is None:
    print("Отправьте сообщение повторно")
else:
    print(f'Исправленное сообщение: {decoded_word}')

Синдром ошибки: [0 1 1 1 1 0 1 1 0 0 1 0]
Вес Хэмминга синдрома больше 3
Не существует строк матрицы B, таких, что wt(s+b[i]) <=2
Вес Хэмминга второго синдрома(s*B) больше 3
Существует строка 1 матрицы B, такая, что wt(s*B+b[i]) <=2
Ошибка: [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
Исправленное сообщение: [1 0 0 0 0 0 0 0 0 0 0 0]


Четырёхкратная ошибка

In [10]:
error_four = np.array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])
err_code = code_word ^ error_four

decoded_word = golay_approach(H, B, err_code)
if decoded_word is None:
    print("Отправьте сообщение повторно")
else:
    print(f'Исправленное сообщение: {decoded_word}')

Синдром ошибки: [0 1 0 1 1 0 1 1 0 0 1 0]
Вес Хэмминга синдрома больше 3
Не существует строк матрицы B, таких, что wt(s+b[i]) <=2
Вес Хэмминга второго синдрома(s*B) больше 3
Не существует строк матрицы B, таких, что wt(s*B+b[i]) <=2
В коде от 4 до 7 ошибок.
Отправьте сообщение повторно


**Все возможные случаи расширенного кода Голея**

In [11]:
error1 = np.array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
error2 = np.array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])
error3 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1])
error4 = np.array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])
error5 = np.array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

errors = [error1, error2, error3, error4, error5]
for er in errors:

  err_code = code_word ^ er
  decoded_word = golay_approach(H, B, err_code)
  if decoded_word is None:
      print("Отправьте сообщение повторно")
  else:
      print(f'Исправленное сообщение: {decoded_word}')
  print("\n\n")

Синдром ошибки: [0 1 1 1 0 0 0 0 0 0 0 0]
Вес Хэмминга синдрома меньше или равен 3
Ошибка: [0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Исправленное сообщение: [1 0 0 0 0 0 0 0 0 0 0 0]



Синдром ошибки: [1 1 1 0 1 1 0 1 1 1 0 1]
Вес Хэмминга синдрома больше 3
Существует строка 7 матрицы B, такая, что wt(s+b[i]) <=2
Ошибка: [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
Исправленное сообщение: [1 0 0 0 0 0 0 0 0 0 0 0]



Синдром ошибки: [0 1 1 0 0 1 0 1 0 0 1 0]
Вес Хэмминга синдрома больше 3
Не существует строк матрицы B, таких, что wt(s+b[i]) <=2
Вес Хэмминга второго синдрома(s*B) меньше или равен 3
Ошибка: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
Исправленное сообщение: [1 0 0 0 0 0 0 0 0 0 0 0]



Синдром ошибки: [1 0 0 0 0 1 0 0 0 1 1 1]
Вес Хэмминга синдрома больше 3
Не существует строк матрицы B, таких, что wt(s+b[i]) <=2
Вес Хэмминга второго синдрома(s*B) больше 3
Существует строка 2 матрицы B, такая, что wt(s*B+b[i]) <=2
Ошибка: [0 0 1 0 0 0 0 0 0 0 0 0 0 0 

**Часть 2**

In [12]:
def kronecker_H_i(i:int, m: int) -> np.ndarray[np.ndarray[int]]:
  k = 2**(i-1)
  part = np.eye(2**i, dtype=int)
  part[k:, k:] *= -1
  for j in range(k):
    part[k+j, j] = part[j, k+j] = 1
  if m == i:
    return part
  k *= 2
  H = np.zeros((2**m, 2**m), dtype=int)
  for j in range(2**(m-i)):
    H[j*k:(j+1)*k, j*k:(j+1)*k] = part
  return H

In [13]:
def G_RM(r:int, m: int) -> np.ndarray[np.ndarray[int]]:
    if r == 0:
        return np.ones((1, 2**m), dtype=int)
    if r == m:
        x = np.zeros((1, 2**m), dtype=int)
        x[0, -1] = 1
        return np.vstack((G_RM(m-1,m), x))
    G_up = G_RM(r, m-1)
    G_down = G_RM(r-1, m-1)
    length_G_up = len(G_up)
    G = np.zeros((len(G_down) + length_G_up, 2**m), dtype=int)
    G[:length_G_up, :2 ** (m-1)] = G_up
    G[:length_G_up, 2 ** (m - 1):] = G_up
    G[length_G_up:, 2 ** (m-1):] = G_down
    return G

**𝑅𝑀(1,3)**

In [14]:
m = 3
G = G_RM(1, m)
G

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1]])

In [15]:
H = np.array([kronecker_H_i(i, m) for i in range(1, m+1)])
H

array([[[ 1,  1,  0,  0,  0,  0,  0,  0],
        [ 1, -1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  1,  1,  0,  0,  0,  0],
        [ 0,  0,  1, -1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  1,  1,  0,  0],
        [ 0,  0,  0,  0,  1, -1,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  1,  1],
        [ 0,  0,  0,  0,  0,  0,  1, -1]],

       [[ 1,  0,  1,  0,  0,  0,  0,  0],
        [ 0,  1,  0,  1,  0,  0,  0,  0],
        [ 1,  0, -1,  0,  0,  0,  0,  0],
        [ 0,  1,  0, -1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  1,  0,  1,  0],
        [ 0,  0,  0,  0,  0,  1,  0,  1],
        [ 0,  0,  0,  0,  1,  0, -1,  0],
        [ 0,  0,  0,  0,  0,  1,  0, -1]],

       [[ 1,  0,  0,  0,  1,  0,  0,  0],
        [ 0,  1,  0,  0,  0,  1,  0,  0],
        [ 0,  0,  1,  0,  0,  0,  1,  0],
        [ 0,  0,  0,  1,  0,  0,  0,  1],
        [ 1,  0,  0,  0, -1,  0,  0,  0],
        [ 0,  1,  0,  0,  0, -1,  0,  0],
        [ 0,  0,  1,  0,  0,  0, -1,  0],
        [ 0,  0,  0,  1,  0,  

In [16]:
word = np.array([1, 0, 1, 0])
w = np.dot(word, G)%2
w

array([1, 1, 0, 0, 1, 1, 0, 0])

In [17]:
e1 = np.zeros_like(w)
e2 = e1.copy()
e1[0] = e2[0] = e2[2] = 1
w1 = w^e1
w2 = w^e2
w1, w2

(array([0, 1, 0, 0, 1, 1, 0, 0]), array([0, 1, 1, 0, 1, 1, 0, 0]))

In [18]:
def find_word(H: np.ndarray[np.ndarray[np.ndarray[int]]], G: np.ndarray[np.ndarray[int]], w_: np.ndarray[int], m: int):
    w_ = np.copy(w_)
    w_ -= w_ ^ 1
    for i in range(m):
        w_ = np.dot(w_, H[i])
    position = 0
    x = abs(w_[0])
    for i in range(1, w_.size):
        if abs(w_[i]) >= x:
            if x == abs(w_[i]):
                position = -1
                continue
            position = i
            x = abs(w_[i])
    if position == -1:
        print("ошибку нельзя исправить!")
        return None
    orig = np.copy(G[:, position]).reshape(-1)
    if w_[position] < 0:
        orig[0] = 0
    return orig

In [19]:
decoded_word = find_word(H, G, w1, m)
if decoded_word is not None:
  print(decoded_word)
  print(np.array_equal(decoded_word, word))

[1 0 1 0]
True


In [20]:
decoded_word = find_word(H, G, w2, m)
if decoded_word is not None:
  print(decoded_word)
  print(np.array_equal(decoded_word, word))

ошибку нельзя исправить!


**𝑅𝑀(1,4)**

In [21]:
m = 4
G = G_RM(1, m)
G

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
H = np.array([kronecker_H_i(i, m) for i in range(1, m+1)])
H

array([[[ 1,  1,  0, ...,  0,  0,  0],
        [ 1, -1,  0, ...,  0,  0,  0],
        [ 0,  0,  1, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ..., -1,  0,  0],
        [ 0,  0,  0, ...,  0,  1,  1],
        [ 0,  0,  0, ...,  0,  1, -1]],

       [[ 1,  0,  1, ...,  0,  0,  0],
        [ 0,  1,  0, ...,  0,  0,  0],
        [ 1,  0, -1, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ...,  1,  0,  1],
        [ 0,  0,  0, ...,  0, -1,  0],
        [ 0,  0,  0, ...,  1,  0, -1]],

       [[ 1,  0,  0, ...,  0,  0,  0],
        [ 0,  1,  0, ...,  0,  0,  0],
        [ 0,  0,  1, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ..., -1,  0,  0],
        [ 0,  0,  0, ...,  0, -1,  0],
        [ 0,  0,  0, ...,  0,  0, -1]],

       [[ 1,  0,  0, ...,  0,  0,  0],
        [ 0,  1,  0, ...,  0,  0,  0],
        [ 0,  0,  1, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ..., -1,  0,  0],
        [ 0,  0,  0, ...,  0, -1,  0],
        [ 0,  0,  0, ...,  0,  0, -1]]])

In [23]:
word = np.array([1, 1, 0, 0, 1])
w = np.dot(word, G)%2
w

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1])

In [24]:
e1 = np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
e2 = np.array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
e3 = np.array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
e4 = np.array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0])
err = [e1, e2, e3, e4]
w_arr = [w ^ e for e in err]
w_arr

[array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1]),
 array([1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1]),
 array([1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1])]

In [26]:
for i in range(len(w_arr)):
  print(f'\n{i+1}-кратная ошибка:')
  decoded_word = find_word(H, G, w_arr[i], m)
  if decoded_word is not None:
    print(np.array_equal(decoded_word, word))


1-кратная ошибка:
True

2-кратная ошибка:
True

3-кратная ошибка:
True

4-кратная ошибка:
ошибку нельзя исправить!
